MAINT: added diverse weighted classifiers
qiime2/resources pull request #10
Opened 2024-07-31 23:34 UTC by hagenjp

I did not add the experimental tag to silva human stool weights because the Bacteriodes classifications were consistent on that classifer
@gregcaporaso do you think it would be better to put the tag on both silva and gtdb to be safe?
additionally do we want to add a write up on how these classifiers were weighted? @cherman2 had mentioned this was an issue when we were moving forward to reproduce the previous classifiers

2024-08-14 19:50 UTC, gregcaporaso commented
@hagenjp, sorry it's taken forever for me to get to this! Two things:

1) I don't think it hurts to tag the Silva human weighted classifier as experiment. It looks like you already did that? 
2) I think it would be good to describe what "diverse" means in this context, maybe in the notes field? I think that would align with @cherman2's comment about noting how the classifiers are weighted.

2024-09-04 23:11 UTC, cherman2 commented on index.md
> +**Notes**: [Silva species taxonomy may be unreliable](#Silva)\
```suggestion
**Notes**: [Silva species taxonomy may be unreliable. These classifiers were created with 14 diverse environments: "Sediment (non-saline)", "Plant corpus", "Animal secretion", "Sediment (saline)", "Animal surface", "Surface (saline)",  "Plant rhizosphere",  "Soil (non-saline)", "Animal distal gut", "Water (saline)",  "Animal proximal gut", "Water (non-saline)",  "Animal corpus", "Plant surface". More information can be found at: https://www.nature.com/articles/s41467-019-12669-6#Sec7 ](#Silva)\
```

2024-09-04 23:12 UTC, cherman2 commented on index.md
> +**Citations**: @Parks2021, @Parks2020, @Parks2018, @Rinke2021
```suggestion
**Date Trained**: 2024-07-09\
**Notes**: [These classifiers were created with 14 diverse environments: "Sediment (non-saline)", "Plant corpus", "Animal secretion", "Sediment (saline)", "Animal surface", "Surface (saline)",  "Plant rhizosphere",  "Soil (non-saline)", "Animal distal gut", "Water (saline)",  "Animal proximal gut", "Water (non-saline)",  "Animal corpus", "Plant surface". More information can be found at: https://www.nature.com/articles/s41467-019-12669-6#Sec7 ](#GTDB)\
**Citations**: @Parks2021, @Parks2020, @Parks2018, @Rinke2021
```

2024-09-04 23:14 UTC, cherman2 reviewed
Hi All, 
Added my suggestions for the diverse classifier note. 

Also we need to add the clawback citation in.

2024-09-04 23:14 UTC, cherman2 commented on index.md
> +**Notes**: [Silva species taxonomy may be unreliable](#Silva)\
We also need to add the clawback citation: https://www.nature.com/articles/s41467-019-12669-6

2024-09-23 18:06 UTC, hagenjp commented
@cherman2 I just went to add it and realized it is already there in the references, line 152! I think we are g2g.

2024-09-23 23:00 UTC, hagenjp commented
@cherman2 okay now it is ready!

2024-09-25 18:14 UTC, cherman2 requested changes
Looks like there are a couple of places where the citations are missings. 
Also, there was a couple of sneaky white spaces so I suggested edits there. Feel free to reject if there is a reason for that white space that I am unaware of. :)

2024-09-25 18:14 UTC, cherman2 commented on index.md
> +**Citations**: @Parks2021, @Parks2020, @Parks2018, @Rinke2021
add cite here

2024-09-25 18:14 UTC, cherman2 commented on index.md
> +**Citations**: @Robeson2020-ax, @Bokulich2018-yb, [Silva](#Silva-Citations)
add cite here

2024-09-25 18:14 UTC, cherman2 commented on index.md
> +**Citations**: @Parks2021, @Parks2020, @Parks2018, @Rinke2021,  @Kaehler2019-lq
```suggestion
**Citations**: @Parks2021, @Parks2020, @Parks2018, @Rinke2021, @Kaehler2019-lq
```
Double white space

2024-09-25 18:14 UTC, cherman2 commented on index.md
> +**Citations**: @Robeson2020-ax, @Bokulich2018-yb,  @Kaehler2019-lq [Silva](#Silva-Citations)
```suggestion
**Citations**: @Robeson2020-ax, @Bokulich2018-yb, @Kaehler2019-lq [Silva](#Silva-Citations)
```
Double white space

2024-09-25 22:47 UTC, cherman2 commented
Alright, Looks good to me. 

@hagenjp, I am going to assign this to Greg for his final approval

2024-09-25 22:47 UTC, cherman2 approved these changes

2024-09-26 19:12 UTC, gregcaporaso approved these changes

2024-09-26 19:12 UTC, merged